#pragma once

#include "../../Clutch/HiHatProperties.h"
#include "../../Utility/CustomComboBox.h"
#include "../../Utility/CustomTextEditor.h"
#include "../../Utility/NoArrowComboBoxLnF.h"

class HiHatEditorComponent : public juce::Component
{
public:
    HiHatEditorComponent ();
    ~HiHatEditorComponent ();

    void init (juce::ValueTree rootPropertiesVT);

    void initializeCallbacks ();

private:
    HiHatProperties hiHatProperties;

    NoArrowComboBoxLnF noArrowComboBoxLnF;

    CustomTextEditorDouble accClAmpModEditor;
    juce::Label accClAmpModLabel;
    CustomTextEditorDouble accClRelModEditor;
    juce::Label accClRelModLabel;
    CustomTextEditorDouble accOpAmpModEditor;
    juce::Label accOpAmpModLabel;
    CustomTextEditorDouble accOpRelModEditor;
    juce::Label accOpRelModLabel;
    CustomTextEditorDouble chokeReleaseEditor;
    juce::Label chokeReleaseLabel;
    CustomTextEditorDouble clsdMaxReleaseEditor;
    juce::Label clsdMaxReleaseLabel;
    CustomTextEditorDouble  clsdRelOfstScaleEditor;
    juce::Label clsdRelOfstScaleLabel;
    CustomComboBox clsdReleaseModeEditor;
    juce::Label clsdReleaseModeLabel;
    CustomComboBox cvDisableFxEditor;
    juce::Label cvDisableFxLabel;
    CustomComboBox cvDisableVelocityEditor;
    juce::Label cvDisableVelocityLabel;
    CustomTextEditorDouble envelopeMaxReleaseEditor;
    juce::Label envelopeMaxReleaseLabel;
    CustomTextEditorDouble feelAmpModEditor;
    juce::Label feelAmpModLabel;
    CustomTextEditorDouble feelAttackModEditor;
    juce::Label feelAttackModLabel;
    CustomTextEditorDouble feelReleaseModEditor;
    juce::Label feelReleaseModLabel;
    CustomTextEditorInt fltrHpfMaxFreqEditor;
    juce::Label fltrHpfMaxFreqLabel;
    CustomTextEditorInt fltrHpfMinFreqEditor;
    juce::Label fltrHpfMinFreqLabel;
    CustomTextEditorDouble fltrHpfQEditor;
    juce::Label fltrHpfQLabel;
    CustomTextEditorInt fltrLpfMaxFreqEditor;
    juce::Label fltrLpfMaxFreqLabel;
    CustomTextEditorInt fltrLpfMinFreqEditor;
    juce::Label fltrLpfMinFreqLabel;
    CustomTextEditorDouble fltrLpfQEditor;
    juce::Label fltrLpfQLabel;
    CustomTextEditorDouble fxChorusCenterEditor;
    juce::Label fxChorusCenterLabel;
    CustomTextEditorDouble fxChorusDepthEditor;
    juce::Label fxChorusDepthLabel;
    CustomTextEditorDouble fxChorusLfoBEditor;
    juce::Label fxChorusLfoBLabel;
    CustomTextEditorInt fxChorusLfoTEditor;
    juce::Label fxChorusLfoTLabel;
    CustomTextEditorDouble fxChorusMixEditor;
    juce::Label fxChorusMixLabel;
    CustomTextEditorDouble fxChorusSpreadEditor;
    juce::Label fxChorusSpreadLabel;
    CustomComboBox fxChorusTapsEditor;
    juce::Label fxChorusTapsLabel;
    CustomComboBox fxCvUnipolarEditor;
    juce::Label fxCvUnipolarLabel;
    CustomTextEditorInt fxDjfilterHpfMaxEditor;
    juce::Label fxDjfilterHpfMaxLabel;
    CustomTextEditorInt fxDjfilterHpfMinEditor;
    juce::Label fxDjfilterHpfMinLabel;
    CustomTextEditorInt fxDjfilterLpfMaxEditor;
    juce::Label fxDjfilterLpfMaxLabel;
    CustomTextEditorInt fxDjfilterLpfMinEditor;
    juce::Label fxDjfilterLpfMinLabel;
    CustomTextEditorDouble fxDjfilterQGainReductionEditor;
    juce::Label fxDjfilterQGainReductionLabel;
    CustomTextEditorDouble fxDjfilterQMaxEditor;
    juce::Label fxDjfilterQMaxLabel;
    CustomTextEditorDouble fxDjfilterQMinEditor;
    juce::Label fxDjfilterQMinLabel;
    CustomTextEditorInt fxDubEchoHpfEditor;
    juce::Label fxDubEchoHpfLabel;
    CustomTextEditorInt fxDubEchoLpfEditor;
    juce::Label fxDubEchoLpfLabel;
    CustomTextEditorDouble fxDubEchoMixEditor;
    juce::Label fxDubEchoMixLabel;
    CustomTextEditorInt fxDubEchoTminEditor;
    juce::Label fxDubEchoTminLabel;
    CustomTextEditorDouble fxGlitchCrushTimeMaxEditor;
    juce::Label fxGlitchCrushTimeMaxLabel;
    CustomTextEditorDouble fxGlitchCrushTimeMinEditor;
    juce::Label fxGlitchCrushTimeMinLabel;
    CustomTextEditorDouble fxGlitchDropKeepLevelMaxEditor;
    juce::Label fxGlitchDropKeepLevelMaxLabel;
    CustomTextEditorDouble fxGlitchDropKeepLevelMinEditor;
    juce::Label fxGlitchDropKeepLevelMinLabel;
    CustomTextEditorDouble fxGlitchDropKeepTimeMaxEditor;
    juce::Label fxGlitchDropKeepTimeMaxLabel;
    CustomTextEditorDouble fxGlitchDropKeepTimeMinEditor;
    juce::Label fxGlitchDropKeepTimeMinLabel;
    CustomTextEditorDouble fxGlitchMicroloopPlayTMaxEditor;
    juce::Label fxGlitchMicroloopPlayTMaxLabel;
    CustomTextEditorDouble fxGlitchMicroloopPlayTMinEditor;
    juce::Label fxGlitchMicroloopPlayTMinLabel;
    CustomTextEditorDouble fxGlitchMicroloopSmplTMaxEditor;
    juce::Label fxGlitchMicroloopSmplTMaxLabel;
    CustomTextEditorDouble fxGlitchMicroloopSmplTMinEditor;
    juce::Label fxGlitchMicroloopSmplTMinLabel;
    CustomTextEditorDouble fxGlitchProbabilityMaxEditor;
    juce::Label fxGlitchProbabilityMaxLabel;
    CustomTextEditorDouble fxGlitchProbabilityMinEditor;
    juce::Label fxGlitchProbabilityMinLabel;
    CustomTextEditorInt fxGlitchStutterNumMaxEditor;
    juce::Label fxGlitchStutterNumMaxLabel;
    CustomTextEditorInt fxGlitchStutterNumMinEditor;
    juce::Label fxGlitchStutterNumMinLabel;
    CustomTextEditorDouble fxGlitchStutterSmplTMaxEditor;
    juce::Label fxGlitchStutterSmplTMaxLabel;
    CustomTextEditorDouble fxGlitchStutterSmplTMinEditor;
    juce::Label fxGlitchStutterSmplTMinLabel;
    CustomTextEditorInt fxGlitchStutterWindowEditor;
    juce::Label fxGlitchStutterWindowLabel;
    CustomTextEditorDouble fxGlitchWeightCrushHighEditor;
    juce::Label fxGlitchWeightCrushHighLabel;
    CustomTextEditorDouble fxGlitchWeightCrushLowEditor;
    juce::Label fxGlitchWeightCrushLowLabel;
    CustomTextEditorDouble fxGlitchWeightDropHighEditor;
    juce::Label fxGlitchWeightDropHighLabel;
    CustomTextEditorDouble fxGlitchWeightDropLowEditor;
    juce::Label fxGlitchWeightDropLowLabel;
    CustomTextEditorDouble fxGlitchWeightHoldHighEditor;
    juce::Label fxGlitchWeightHoldHighLabel;
    CustomTextEditorDouble fxGlitchWeightHoldLowEditor;
    juce::Label fxGlitchWeightHoldLowLabel;
    CustomTextEditorDouble fxGlitchWeightStutterHighEditor;
    juce::Label fxGlitchWeightStutterHighLabel;
    CustomTextEditorDouble fxGlitchWeightStutterLowEditor;
    juce::Label fxGlitchWeightStutterLowLabel;
    CustomTextEditorInt fxReverbHpfEditor;
    juce::Label fxReverbHpfLabel;
    CustomTextEditorInt fxReverbLpfEditor;
    juce::Label fxReverbLpfLabel;
    CustomComboBox gateModeEditor;
    juce::Label gateModeLabel;
    CustomComboBox knobPosTakeupEditor;
    juce::Label knobPosTakeupLabel;
    CustomTextEditorDouble pitchHighEditor;
    juce::Label pitchHighLabel;
    CustomTextEditorDouble pitchLowEditor;
    juce::Label pitchLowLabel;
    CustomComboBox velocityUnipolarEditor;
    juce::Label velocityUnipolarLabel;

    void pitchLowDataChanged (float value);
    void pitchHighDataChanged (float value);
    void envelopeMaxReleaseDataChanged (float value);
    void chokeReleaseDataChanged (float value);
    void clsdReleaseModeDataChanged (int value);
    void clsdRelOfstScaleDataChanged (float value);
    void clsdMaxReleaseDataChanged (float value);
    void accClRelModDataChanged (float value);
    void accOpRelModDataChanged (float value);
    void accClAmpModDataChanged (float value);
    void accOpAmpModDataChanged (float value);
    void feelAttackModDataChanged (float value);
    void feelReleaseModDataChanged (float value);
    void feelAmpModDataChanged (float value);
    void fxCvUnipolarDataChanged (int value);
    void velocityUnipolarDataChanged (int value);
    void cvDisableVelocityDataChanged (int value);
    void cvDisableFxDataChanged (int value);
    void gateModeDataChanged (int value);
    void knobPosTakeupDataChanged (int value);
    void fltrHpfMinFreqDataChanged (int value);
    void fltrHpfMaxFreqDataChanged (int value);
    void fltrLpfMinFreqDataChanged (int value);
    void fltrLpfMaxFreqDataChanged (int value);
    void fltrHpfQDataChanged (float value);
    void fltrLpfQDataChanged (float value);
    void fxDjfilterHpfMinDataChanged (int value);
    void fxDjfilterHpfMaxDataChanged (int value);
    void fxDjfilterLpfMinDataChanged (int value);
    void fxDjfilterLpfMaxDataChanged (int value);
    void fxDjfilterQMinDataChanged (float value);
    void fxDjfilterQMaxDataChanged (float value);
    void fxDjfilterQGainReductionDataChanged (float value);
    void fxDubEchoTminDataChanged (int value);
    void fxDubEchoHpfDataChanged (int value);
    void fxDubEchoLpfDataChanged (int value);
    void fxDubEchoMixDataChanged (float value);
    void fxChorusCenterDataChanged (float value);
    void fxChorusDepthDataChanged (float value);
    void fxChorusMixDataChanged (float value);
    void fxChorusSpreadDataChanged (float value);
    void fxChorusTapsDataChanged (int value);
    void fxChorusLfoBDataChanged (float value);
    void fxChorusLfoTDataChanged (int value);
    void fxReverbLpfDataChanged (int value);
    void fxReverbHpfDataChanged (int value);
    void fxGlitchProbabilityMinDataChanged (float value);
    void fxGlitchProbabilityMaxDataChanged (float value);
    void fxGlitchWeightHoldLowDataChanged (float value);
    void fxGlitchWeightStutterLowDataChanged (float value);
    void fxGlitchWeightCrushLowDataChanged (float value);
    void fxGlitchWeightDropLowDataChanged (float value);
    void fxGlitchWeightHoldHighDataChanged (float value);
    void fxGlitchWeightStutterHighDataChanged (float value);
    void fxGlitchWeightCrushHighDataChanged (float value);
    void fxGlitchWeightDropHighDataChanged (float value);
    void fxGlitchDropKeepLevelMinDataChanged (float value);
    void fxGlitchDropKeepLevelMaxDataChanged (float value);
    void fxGlitchDropKeepTimeMinDataChanged (float value);
    void fxGlitchDropKeepTimeMaxDataChanged (float value);
    void fxGlitchCrushTimeMinDataChanged (float value);
    void fxGlitchCrushTimeMaxDataChanged (float value);
    void fxGlitchMicroloopSmplTMinDataChanged (float value);
    void fxGlitchMicroloopSmplTMaxDataChanged (float value);
    void fxGlitchMicroloopPlayTMinDataChanged (float value);
    void fxGlitchMicroloopPlayTMaxDataChanged (float value);
    void fxGlitchStutterSmplTMinDataChanged (float value);
    void fxGlitchStutterSmplTMaxDataChanged (float value);
    void fxGlitchStutterNumMinDataChanged (int value);
    void fxGlitchStutterNumMaxDataChanged (int value);
    void fxGlitchStutterWindowDataChanged (int value);

    void pitchLowUiChanged (float value);
    void pitchHighUiChanged (float value);
    void envelopeMaxReleaseUiChanged (float value);
    void chokeReleaseUiChanged (float value);
    void clsdReleaseModeUiChanged (int value);
    void clsdRelOfstScaleUiChanged (float value);
    void clsdMaxReleaseUiChanged (float value);
    void accClRelModUiChanged (float value);
    void accOpRelModUiChanged (float value);
    void accClAmpModUiChanged (float value);
    void accOpAmpModUiChanged (float value);
    void feelAttackModUiChanged (float value);
    void feelReleaseModUiChanged (float value);
    void feelAmpModUiChanged (float value);
    void fxCvUnipolarUiChanged (int value);
    void velocityUnipolarUiChanged (int value);
    void cvDisableVelocityUiChanged (int value);
    void cvDisableFxUiChanged (int value);
    void gateModeUiChanged (int value);
    void knobPosTakeupUiChanged (int value);
    void fltrHpfMinFreqUiChanged (int value);
    void fltrHpfMaxFreqUiChanged (int value);
    void fltrLpfMinFreqUiChanged (int value);
    void fltrLpfMaxFreqUiChanged (int value);
    void fltrHpfQUiChanged (float value);
    void fltrLpfQUiChanged (float value);
    void fxDjfilterHpfMinUiChanged (int value);
    void fxDjfilterHpfMaxUiChanged (int value);
    void fxDjfilterLpfMinUiChanged (int value);
    void fxDjfilterLpfMaxUiChanged (int value);
    void fxDjfilterQMinUiChanged (float value);
    void fxDjfilterQMaxUiChanged (float value);
    void fxDjfilterQGainReductionUiChanged (float value);
    void fxDubEchoTminUiChanged (int value);
    void fxDubEchoHpfUiChanged (int value);
    void fxDubEchoLpfUiChanged (int value);
    void fxDubEchoMixUiChanged (float value);
    void fxChorusCenterUiChanged (float value);
    void fxChorusDepthUiChanged (float value);
    void fxChorusMixUiChanged (float value);
    void fxChorusSpreadUiChanged (float value);
    void fxChorusTapsUiChanged (int value);
    void fxChorusLfoBUiChanged (float value);
    void fxChorusLfoTUiChanged (int value);
    void fxReverbLpfUiChanged (int value);
    void fxReverbHpfUiChanged (int value);
    void fxGlitchProbabilityMinUiChanged (float value);
    void fxGlitchProbabilityMaxUiChanged (float value);
    void fxGlitchWeightHoldLowUiChanged (float value);
    void fxGlitchWeightStutterLowUiChanged (float value);
    void fxGlitchWeightCrushLowUiChanged (float value);
    void fxGlitchWeightDropLowUiChanged (float value);
    void fxGlitchWeightHoldHighUiChanged (float value);
    void fxGlitchWeightStutterHighUiChanged (float value);
    void fxGlitchWeightCrushHighUiChanged (float value);
    void fxGlitchWeightDropHighUiChanged (float value);
    void fxGlitchDropKeepLevelMinUiChanged (float value);
    void fxGlitchDropKeepLevelMaxUiChanged (float value);
    void fxGlitchDropKeepTimeMinUiChanged (float value);
    void fxGlitchDropKeepTimeMaxUiChanged (float value);
    void fxGlitchCrushTimeMinUiChanged (float value);
    void fxGlitchCrushTimeMaxUiChanged (float value);
    void fxGlitchMicroloopSmplTMinUiChanged (float value);
    void fxGlitchMicroloopSmplTMaxUiChanged (float value);
    void fxGlitchMicroloopPlayTMinUiChanged (float value);
    void fxGlitchMicroloopPlayTMaxUiChanged (float value);
    void fxGlitchStutterSmplTMinUiChanged (float value);
    void fxGlitchStutterSmplTMaxUiChanged (float value);
    void fxGlitchStutterNumMinUiChanged (int value);
    void fxGlitchStutterNumMaxUiChanged (int value);
    void fxGlitchStutterWindowUiChanged (int value);

    void paint (juce::Graphics& g) override;
    void resized () override;
};