#pragma once

#include "../../Clutch/HiHatProperties.h"
#include "../../Utility/CustomComboBox.h"
#include "../../Utility/CustomTextEditor.h"

class HiHatEditorComponent : public juce::Component
{
public:
    HiHatEditorComponent ();
    ~HiHatEditorComponent ();

    void init (juce::ValueTree rootPropertiesVT);

    void initializeCallbacks ();
    void accClAmpModDataChanged (int value);
    void accClAmpModUiChanged (int value);
private:
    HiHatProperties hiHatProperties;

    CustomTextEditorDouble accClAmpModEditor;
    juce::Label accClAmpModLabel;
    CustomTextEditorDouble accClRelModEditor;
    juce::Label accClRelModLabel;
    CustomTextEditorDouble accOpAmpModEditor;
    juce::Label accOpAmpModLabel;
    CustomTextEditorDouble accOpRelModEditor;
    juce::Label accOpRelModLabel;
    CustomTextEditorDouble chokeReleaseEditor;
    juce::Label chokeReleaseLabel;
    CustomTextEditorDouble clsdMaxReleaseEditor;
    juce::Label clsdMaxReleaseLabel;
    CustomTextEditorDouble  clsdRelOfstScaleEditor;
    juce::Label clsdRelOfstScaleLabel;
    CustomComboBox clsdReleaseModeEditor;
    juce::Label clsdReleaseModeLabel;
    CustomComboBox cvDisableFxEditor;
    juce::Label cvDisableFxLabel;
    CustomComboBox cvDisableVelocityEditor;
    juce::Label cvDisableVelocityLabel;
    CustomTextEditorDouble envelopeMaxReleaseEditor;
    juce::Label envelopeMaxReleaseLabel;
    CustomTextEditorDouble feelAmpModEditor;
    juce::Label feelAmpModLabel;
    CustomTextEditorDouble feelAttackModEditor;
    juce::Label feelAttackModLabel;
    CustomTextEditorDouble feelReleaseModEditor;
    juce::Label feelReleaseModLabel;
    CustomTextEditorInt fltrHpfMaxFreqEditor;
    juce::Label fltrHpfMaxFreqLabel;
    CustomTextEditorInt fltrHpfMinFreqEditor;
    juce::Label fltrHpfMinFreqLabel;
    CustomTextEditorDouble fltrHpfQEditor;
    juce::Label fltrHpfQLabel;
    CustomTextEditorInt fltrLpfMaxFreqEditor;
    juce::Label fltrLpfMaxFreqLabel;
    CustomTextEditorInt fltrLpfMinFreqEditor;
    juce::Label fltrLpfMinFreqLabel;
    CustomTextEditorDouble fltrLpfQEditor;
    juce::Label fltrLpfQLabel;
    CustomTextEditorDouble fxChorusCenterEditor;
    juce::Label fxChorusCenterLabel;
    CustomTextEditorDouble fxChorusDepthEditor;
    juce::Label fxChorusDepthLabel;
    CustomTextEditorDouble fxChorusLfoBEditor;
    juce::Label fxChorusLfoBLabel;
    CustomTextEditorInt fxChorusLfoTEditor;
    juce::Label fxChorusLfoTLabel;
    CustomTextEditorDouble fxChorusMixEditor;
    juce::Label fxChorusMixLabel;
    CustomTextEditorDouble fxChorusSpreadEditor;
    juce::Label fxChorusSpreadLabel;
    CustomComboBox fxChorusTapsEditor;
    juce::Label fxChorusTapsLabel;
    CustomComboBox fxCvUnipolarEditor;
    juce::Label fxCvUnipolarLabel;
    CustomTextEditorInt fxDjfilterHpfMaxEditor;
    juce::Label fxDjfilterHpfMaxLabel;
    CustomTextEditorInt fxDjfilterHpfMinEditor;
    juce::Label fxDjfilterHpfMinLabel;
    CustomTextEditorInt fxDjfilterLpfMaxEditor;
    juce::Label fxDjfilterLpfMaxLabel;
    CustomTextEditorInt fxDjfilterLpfMinEditor;
    juce::Label fxDjfilterLpfMinLabel;
    CustomTextEditorDouble fxDjfilterQGainReductionEditor;
    juce::Label fxDjfilterQGainReductionLabel;
    CustomTextEditorDouble fxDjfilterQMaxEditor;
    juce::Label fxDjfilterQMaxLabel;
    CustomTextEditorDouble fxDjfilterQMinEditor;
    juce::Label fxDjfilterQMinLabel;
    CustomTextEditorInt fxDubEchoHpfEditor;
    juce::Label fxDubEchoHpfLabel;
    CustomTextEditorInt fxDubEchoLpfEditor;
    juce::Label fxDubEchoLpfLabel;
    CustomTextEditorDouble fxDubEchoMixEditor;
    juce::Label fxDubEchoMixLabel;
    CustomTextEditorInt fxDubEchoTminEditor;
    juce::Label fxDubEchoTminLabel;
    CustomTextEditorDouble fxGlitchCrushTimeMaxEditor;
    juce::Label fxGlitchCrushTimeMaxLabel;
    CustomTextEditorDouble fxGlitchCrushTimeMinEditor;
    juce::Label fxGlitchCrushTimeMinLabel;
    CustomTextEditorDouble fxGlitchDropKeepLevelMaxEditor;
    juce::Label fxGlitchDropKeepLevelMaxLabel;
    CustomTextEditorDouble fxGlitchDropKeepLevelMinEditor;
    juce::Label fxGlitchDropKeepLevelMinLabel;
    CustomTextEditorDouble fxGlitchDropKeepTimeMaxEditor;
    juce::Label fxGlitchDropKeepTimeMaxLabel;
    CustomTextEditorDouble fxGlitchDropKeepTimeMinEditor;
    juce::Label fxGlitchDropKeepTimeMinLabel;
    CustomTextEditorDouble fxGlitchMicroloopPlayTMaxEditor;
    juce::Label fxGlitchMicroloopPlayTMaxLabel;
    CustomTextEditorDouble fxGlitchMicroloopPlayTMinEditor;
    juce::Label fxGlitchMicroloopPlayTMinLabel;
    CustomTextEditorDouble fxGlitchMicroloopSmplTMaxEditor;
    juce::Label fxGlitchMicroloopSmplTMaxLabel;
    CustomTextEditorDouble fxGlitchMicroloopSmplTMinEditor;
    juce::Label fxGlitchMicroloopSmplTMinLabel;
    CustomTextEditorDouble fxGlitchProbabilityMaxEditor;
    juce::Label fxGlitchProbabilityMaxLabel;
    CustomTextEditorDouble fxGlitchProbabilityMinEditor;
    juce::Label fxGlitchProbabilityMinLabel;
    CustomTextEditorInt fxGlitchStutterNumMaxEditor;
    juce::Label fxGlitchStutterNumMaxLabel;
    CustomTextEditorInt fxGlitchStutterNumMinEditor;
    juce::Label fxGlitchStutterNumMinLabel;
    CustomTextEditorDouble fxGlitchStutterSmplTMaxEditor;
    juce::Label fxGlitchStutterSmplTMaxLabel;
    CustomTextEditorDouble fxGlitchStutterSmplTMinEditor;
    juce::Label fxGlitchStutterSmplTMinLabel;
    CustomTextEditorInt fxGlitchStutterWindowEditor;
    juce::Label fxGlitchStutterWindowLabel;
    CustomTextEditorDouble fxGlitchWeightCrushHighEditor;
    juce::Label fxGlitchWeightCrushHighLabel;
    CustomTextEditorDouble fxGlitchWeightCrushLowEditor;
    juce::Label fxGlitchWeightCrushLowLabel;
    CustomTextEditorDouble fxGlitchWeightDropHighEditor;
    juce::Label fxGlitchWeightDropHighLabel;
    CustomTextEditorDouble fxGlitchWeightDropLowEditor;
    juce::Label fxGlitchWeightDropLowLabel;
    CustomTextEditorDouble fxGlitchWeightHoldHighEditor;
    juce::Label fxGlitchWeightHoldHighLabel;
    CustomTextEditorDouble fxGlitchWeightHoldLowEditor;
    juce::Label fxGlitchWeightHoldLowLabel;
    CustomTextEditorDouble fxGlitchWeightStutterHighEditor;
    juce::Label fxGlitchWeightStutterHighLabel;
    CustomTextEditorDouble fxGlitchWeightStutterLowEditor;
    juce::Label fxGlitchWeightStutterLowLabel;
    CustomTextEditorInt fxReverbHpfEditor;
    juce::Label fxReverbHpfLabel;
    CustomTextEditorInt fxReverbLpfEditor;
    juce::Label fxReverbLpfLabel;
    CustomComboBox gateModeEditor;
    juce::Label gateModeLabel;
    CustomComboBox knobPosTakeupEditor;
    juce::Label knobPosTakeupLabel;
    CustomTextEditorDouble pitchHighEditor;
    juce::Label pitchHighLabel;
    CustomTextEditorDouble pitchLowEditor;
    juce::Label pitchLowLabel;
    CustomComboBox velocityUnipolarEditor;
    juce::Label velocityUnipolarLabel;

    void paint (juce::Graphics& g) override;
    void resized () override;
};