#pragma once

#include "../../Clutch/SettingsProperties.h"
#include "oolib/GUI/CustomComboBox.h"
#include "oolib/GUI/CustomTextEditor.h"
#include "oolib/GUI/NoArrowComboBoxLnF.h"

class SettingsEditorComponent : public juce::Component
{
public:
    SettingsEditorComponent ();
    ~SettingsEditorComponent ();

    void init (juce::ValueTree rootPropertiesVT);

    void initializeCallbacks ();

private:
    SettingsProperties settingsProperties;
    SettingsProperties uneditedSettingsProperties;

    NoArrowComboBoxLnF noArrowComboBoxLnF;

    CustomTextEditorFloat accClAmpModEditor;
    juce::Label accClAmpModLabel;
    CustomTextEditorFloat accClRelModEditor;
    juce::Label accClRelModLabel;
    CustomTextEditorFloat accOpAmpModEditor;
    juce::Label accOpAmpModLabel;
    CustomTextEditorFloat accOpRelModEditor;
    juce::Label accOpRelModLabel;
    CustomTextEditorFloat chokeReleaseEditor;
    juce::Label chokeReleaseLabel;
    CustomTextEditorFloat clsdMaxReleaseEditor;
    juce::Label clsdMaxReleaseLabel;
    CustomTextEditorFloat  clsdRelOfstScaleEditor;
    juce::Label clsdRelOfstScaleLabel;
    CustomComboBox releaseModeComboBox;
    juce::Label releaseModeLabel;
    CustomComboBox cvDisableFxComboBox;
    juce::Label cvDisableFxLabel;
    CustomComboBox cvDisableVelocityComboBox;
    juce::Label cvDisableVelocityLabel;
    CustomTextEditorFloat envelopeMaxReleaseEditor;
    juce::Label envelopeMaxReleaseLabel;
    CustomTextEditorFloat feelAmpModEditor;
    juce::Label feelAmpModLabel;
    CustomTextEditorFloat feelAttackModEditor;
    juce::Label feelAttackModLabel;
    CustomTextEditorFloat feelReleaseModEditor;
    juce::Label feelReleaseModLabel;
    CustomTextEditorInt fltrHpfMaxFreqEditor;
    juce::Label fltrHpfMaxFreqLabel;
    CustomTextEditorInt fltrHpfMinFreqEditor;
    juce::Label fltrHpfMinFreqLabel;
    CustomTextEditorFloat fltrHpfQEditor;
    juce::Label fltrHpfQLabel;
    CustomTextEditorInt fltrLpfMaxFreqEditor;
    juce::Label fltrLpfMaxFreqLabel;
    CustomTextEditorInt fltrLpfMinFreqEditor;
    juce::Label fltrLpfMinFreqLabel;
    CustomTextEditorFloat fltrLpfQEditor;
    juce::Label fltrLpfQLabel;
    CustomTextEditorFloat fxChorusCenterEditor;
    juce::Label fxChorusCenterLabel;
    CustomTextEditorFloat fxChorusDepthEditor;
    juce::Label fxChorusDepthLabel;
    CustomTextEditorFloat fxChorusLfoBEditor;
    juce::Label fxChorusLfoBLabel;
    CustomTextEditorFloat fxChorusLfoTEditor;
    juce::Label fxChorusLfoTLabel;
    CustomTextEditorFloat fxChorusMixEditor;
    juce::Label fxChorusMixLabel;
    CustomTextEditorFloat fxChorusSpreadEditor;
    juce::Label fxChorusSpreadLabel;
    CustomTextEditorFloat fxChorusStaggerEditor;
    juce::Label fxChorusStaggerLabel;
    CustomComboBox fxChorusTapsComboBox;
    juce::Label fxChorusTapsLabel;
    CustomComboBox fxChorusTypeComboBox;
    juce::Label fxChorusTypeLabel;
    CustomComboBox fxCvUnipolarComboBox;
    juce::Label fxCvUnipolarLabel;
    CustomTextEditorInt fxDjfilterHpfMaxEditor;
    juce::Label fxDjfilterHpfMaxLabel;
    CustomTextEditorInt fxDjfilterHpfMinEditor;
    juce::Label fxDjfilterHpfMinLabel;
    CustomTextEditorInt fxDjfilterLpfMaxEditor;
    juce::Label fxDjfilterLpfMaxLabel;
    CustomTextEditorInt fxDjfilterLpfMinEditor;
    juce::Label fxDjfilterLpfMinLabel;
    CustomTextEditorFloat fxDjfilterQGainReductionEditor;
    juce::Label fxDjfilterQGainReductionLabel;
    CustomTextEditorFloat fxDjfilterQMaxEditor;
    juce::Label fxDjfilterQMaxLabel;
    CustomTextEditorFloat fxDjfilterQMinEditor;
    juce::Label fxDjfilterQMinLabel;
    CustomTextEditorInt fxDubEchoHpfEditor;
    juce::Label fxDubEchoHpfLabel;
    CustomTextEditorInt fxDubEchoLpfEditor;
    juce::Label fxDubEchoLpfLabel;
    CustomTextEditorFloat fxDubEchoMixEditor;
    juce::Label fxDubEchoMixLabel;
    CustomTextEditorInt fxDubEchoTminEditor;
    juce::Label fxDubEchoTminLabel;
    CustomTextEditorFloat fxGlitchCrushTimeMaxEditor;
    juce::Label fxGlitchCrushTimeMaxLabel;
    CustomTextEditorFloat fxGlitchCrushTimeMinEditor;
    juce::Label fxGlitchCrushTimeMinLabel;
    CustomTextEditorFloat fxGlitchDropKeepLevelMaxEditor;
    juce::Label fxGlitchDropKeepLevelMaxLabel;
    CustomTextEditorFloat fxGlitchDropKeepLevelMinEditor;
    juce::Label fxGlitchDropKeepLevelMinLabel;
    CustomTextEditorFloat fxGlitchDropKeepTimeMaxEditor;
    juce::Label fxGlitchDropKeepTimeMaxLabel;
    CustomTextEditorFloat fxGlitchDropKeepTimeMinEditor;
    juce::Label fxGlitchDropKeepTimeMinLabel;
    CustomTextEditorFloat fxGlitchMicroloopPlayTMaxEditor;
    juce::Label fxGlitchMicroloopPlayTMaxLabel;
    CustomTextEditorFloat fxGlitchMicroloopPlayTMinEditor;
    juce::Label fxGlitchMicroloopPlayTMinLabel;
    CustomTextEditorFloat fxGlitchMicroloopSmplTMaxEditor;
    juce::Label fxGlitchMicroloopSmplTMaxLabel;
    CustomTextEditorFloat fxGlitchMicroloopSmplTMinEditor;
    juce::Label fxGlitchMicroloopSmplTMinLabel;
    CustomTextEditorFloat fxGlitchProbabilityMaxEditor;
    juce::Label fxGlitchProbabilityMaxLabel;
    CustomTextEditorFloat fxGlitchProbabilityMinEditor;
    juce::Label fxGlitchProbabilityMinLabel;
    CustomTextEditorInt fxGlitchStutterNumMaxEditor;
    juce::Label fxGlitchStutterNumMaxLabel;
    CustomTextEditorInt fxGlitchStutterNumMinEditor;
    juce::Label fxGlitchStutterNumMinLabel;
    CustomTextEditorFloat fxGlitchStutterSmplTMaxEditor;
    juce::Label fxGlitchStutterSmplTMaxLabel;
    CustomTextEditorFloat fxGlitchStutterSmplTMinEditor;
    juce::Label fxGlitchStutterSmplTMinLabel;
    CustomTextEditorInt fxGlitchStutterWindowEditor;
    juce::Label fxGlitchStutterWindowLabel;
    CustomTextEditorFloat fxGlitchWeightCrushHighEditor;
    juce::Label fxGlitchWeightCrushHighLabel;
    CustomTextEditorFloat fxGlitchWeightCrushLowEditor;
    juce::Label fxGlitchWeightCrushLowLabel;
    CustomTextEditorFloat fxGlitchWeightDropHighEditor;
    juce::Label fxGlitchWeightDropHighLabel;
    CustomTextEditorFloat fxGlitchWeightDropLowEditor;
    juce::Label fxGlitchWeightDropLowLabel;
    CustomTextEditorFloat fxGlitchWeightHoldHighEditor;
    juce::Label fxGlitchWeightHoldHighLabel;
    CustomTextEditorFloat fxGlitchWeightHoldLowEditor;
    juce::Label fxGlitchWeightHoldLowLabel;
    CustomTextEditorFloat fxGlitchWeightStutterHighEditor;
    juce::Label fxGlitchWeightStutterHighLabel;
    CustomTextEditorFloat fxGlitchWeightStutterLowEditor;
    juce::Label fxGlitchWeightStutterLowLabel;
    CustomTextEditorFloat fxReverbDiffusionEditor;
    juce::Label fxReverbDiffusionLabel;
    CustomTextEditorInt fxReverbHpfEditor;
    juce::Label fxReverbHpfLabel;
    CustomTextEditorInt fxReverbLpfEditor;
    juce::Label fxReverbLpfLabel;
    CustomTextEditorFloat fxReverbMixEditor;
    juce::Label fxReverbMixLabel;
    CustomTextEditorFloat fxReverbModDepthEditor;
    juce::Label fxReverbModDepthLabel;
    CustomTextEditorFloat fxReverbModRateEditor;
    juce::Label fxReverbModRateLabel;
    CustomTextEditorInt fxReverbPredelayEditor;
    juce::Label fxReverbPredelayLabel;
    CustomTextEditorFloat fxReverbSizeMaxEditor;
    juce::Label fxReverbSizeMaxLabel;
    CustomTextEditorFloat fxReverbSizeMinEditor;
    juce::Label fxReverbSizeMinLabel;
    CustomComboBox fxReverbTypeComboBox;
    juce::Label fxReverbTypeLabel;
    CustomComboBox gateModeComboBox;
    juce::Label gateModeLabel;
    CustomComboBox knobPosTakeupComboBox;
    juce::Label knobPosTakeupLabel;
    CustomTextEditorFloat pitchHighEditor;
    juce::Label pitchHighLabel;
    CustomTextEditorFloat pitchLowEditor;
    juce::Label pitchLowLabel;
    CustomComboBox velocityUnipolarComboBox;
    juce::Label velocityUnipolarLabel;

    juce::Label accentHeaderLabel;
    juce::Label accentOpenedHeaderLabel;
    juce::Label accentClosedHeaderLabel;

    juce::Label closedHeaderLabel;

    juce::Label cvHeaderLabel;

    juce::Label envelopeHeaderLabel;
    juce::Label feelHeaderLabel;

    juce::Label filterHeaderLabel;
    juce::Label filterHpfHeaderLabel;
    juce::Label filterLpfHeaderLabel;

    juce::Label pitchHeaderLabel;
    juce::Label utilityHeaderLabel;

    juce::Label chorusHeaderLabel;

    juce::Label djFilterHeaderLabel;
    juce::Label djFilterHpfHeaderLabel;
    juce::Label djFilterLpfHeaderLabel;
    juce::Label djFilterQHeaderLabel;

    juce::Label dubEchoHeaderLabel;

    juce::Label reverbHeaderLabel;

    juce::Label glitchHeaderLabel;
    juce::Label glitchCrushHeaderLabel;
    juce::Label glitchDropHeaderLabel;
    juce::Label glitchMicroloopHeaderLabel;
    juce::Label glitchProbabilityHeaderLabel;
    juce::Label glitchStutterHeaderLabel;
    juce::Label glitchWeightsHeaderLabel;

    std::vector<juce::Rectangle<int>> sectionBoxes;

    void pitchLowDataChanged (float value);
    void pitchHighDataChanged (float value);
    void envelopeMaxReleaseDataChanged (float value);
    void chokeReleaseDataChanged (float value);
    void releaseModeDataChanged (int value);
    void clsdRelOfstScaleDataChanged (float value);
    void clsdMaxReleaseDataChanged (float value);
    void accClRelModDataChanged (float value);
    void accOpRelModDataChanged (float value);
    void accClAmpModDataChanged (float value);
    void accOpAmpModDataChanged (float value);
    void feelAttackModDataChanged (float value);
    void feelReleaseModDataChanged (float value);
    void feelAmpModDataChanged (float value);
    void fxCvUnipolarDataChanged (int value);
    void velocityUnipolarDataChanged (int value);
    void cvDisableVelocityDataChanged (int value);
    void cvDisableFxDataChanged (int value);
    void gateModeDataChanged (int value);
    void knobPosTakeupDataChanged (int value);
    void fltrHpfMinFreqDataChanged (int value);
    void fltrHpfMaxFreqDataChanged (int value);
    void fltrLpfMinFreqDataChanged (int value);
    void fltrLpfMaxFreqDataChanged (int value);
    void fltrHpfQDataChanged (float value);
    void fltrLpfQDataChanged (float value);
    void fxDjfilterHpfMinDataChanged (int value);
    void fxDjfilterHpfMaxDataChanged (int value);
    void fxDjfilterLpfMinDataChanged (int value);
    void fxDjfilterLpfMaxDataChanged (int value);
    void fxDjfilterQMinDataChanged (float value);
    void fxDjfilterQMaxDataChanged (float value);
    void fxDjfilterQGainReductionDataChanged (float value);
    void fxDubEchoTminDataChanged (int value);
    void fxDubEchoHpfDataChanged (int value);
    void fxDubEchoLpfDataChanged (int value);
    void fxDubEchoMixDataChanged (float value);
    void fxChorusCenterDataChanged (float value);
    void fxChorusDepthDataChanged (float value);
    void fxChorusMixDataChanged (float value);
    void fxChorusSpreadDataChanged (float value);
    void fxChorusStaggerDataChanged (float value);
    void fxChorusTapsDataChanged (int value);
    void fxChorusTypeDataChanged (int value);
    void fxChorusLfoBDataChanged (float value);
    void fxChorusLfoTDataChanged (float value);
    void fxReverbLpfDataChanged (int value);
    void fxReverbHpfDataChanged (int value);
    void fxReverbTypeDataChanged (int value);
    void fxReverbSizeMinDataChanged (float value);
    void fxReverbSizeMaxDataChanged (float value);
    void fxReverbPredelayDataChanged (int value);
    void fxReverbModDepthDataChanged (float value);
    void fxReverbModRateDataChanged (float value);
    void fxReverbDiffusionDataChanged (float value);
    void fxReverbMixDataChanged (float value);
    void fxGlitchProbabilityMinDataChanged (float value);
    void fxGlitchProbabilityMaxDataChanged (float value);
    void fxGlitchWeightHoldLowDataChanged (float value);
    void fxGlitchWeightStutterLowDataChanged (float value);
    void fxGlitchWeightCrushLowDataChanged (float value);
    void fxGlitchWeightDropLowDataChanged (float value);
    void fxGlitchWeightHoldHighDataChanged (float value);
    void fxGlitchWeightStutterHighDataChanged (float value);
    void fxGlitchWeightCrushHighDataChanged (float value);
    void fxGlitchWeightDropHighDataChanged (float value);
    void fxGlitchDropKeepLevelMinDataChanged (float value);
    void fxGlitchDropKeepLevelMaxDataChanged (float value);
    void fxGlitchDropKeepTimeMinDataChanged (float value);
    void fxGlitchDropKeepTimeMaxDataChanged (float value);
    void fxGlitchCrushTimeMinDataChanged (float value);
    void fxGlitchCrushTimeMaxDataChanged (float value);
    void fxGlitchMicroloopSmplTMinDataChanged (float value);
    void fxGlitchMicroloopSmplTMaxDataChanged (float value);
    void fxGlitchMicroloopPlayTMinDataChanged (float value);
    void fxGlitchMicroloopPlayTMaxDataChanged (float value);
    void fxGlitchStutterSmplTMinDataChanged (float value);
    void fxGlitchStutterSmplTMaxDataChanged (float value);
    void fxGlitchStutterNumMinDataChanged (int value);
    void fxGlitchStutterNumMaxDataChanged (int value);
    void fxGlitchStutterWindowDataChanged (int value);

    void pitchLowUiChanged (float value);
    void pitchHighUiChanged (float value);
    void envelopeMaxReleaseUiChanged (float value);
    void chokeReleaseUiChanged (float value);
    void releaseModeUiChanged (int value);
    void clsdRelOfstScaleUiChanged (float value);
    void clsdMaxReleaseUiChanged (float value);
    void accClRelModUiChanged (float value);
    void accOpRelModUiChanged (float value);
    void accClAmpModUiChanged (float value);
    void accOpAmpModUiChanged (float value);
    void feelAttackModUiChanged (float value);
    void feelReleaseModUiChanged (float value);
    void feelAmpModUiChanged (float value);
    void fxCvUnipolarUiChanged (int value);
    void velocityUnipolarUiChanged (int value);
    void cvDisableVelocityUiChanged (int value);
    void cvDisableFxUiChanged (int value);
    void gateModeUiChanged (int value);
    void knobPosTakeupUiChanged (int value);
    void fltrHpfMinFreqUiChanged (int value);
    void fltrHpfMaxFreqUiChanged (int value);
    void fltrLpfMinFreqUiChanged (int value);
    void fltrLpfMaxFreqUiChanged (int value);
    void fltrHpfQUiChanged (float value);
    void fltrLpfQUiChanged (float value);
    void fxDjfilterHpfMinUiChanged (int value);
    void fxDjfilterHpfMaxUiChanged (int value);
    void fxDjfilterLpfMinUiChanged (int value);
    void fxDjfilterLpfMaxUiChanged (int value);
    void fxDjfilterQMinUiChanged (float value);
    void fxDjfilterQMaxUiChanged (float value);
    void fxDjfilterQGainReductionUiChanged (float value);
    void fxDubEchoTminUiChanged (int value);
    void fxDubEchoHpfUiChanged (int value);
    void fxDubEchoLpfUiChanged (int value);
    void fxDubEchoMixUiChanged (float value);
    void fxChorusCenterUiChanged (float value);
    void fxChorusDepthUiChanged (float value);
    void fxChorusMixUiChanged (float value);
    void fxChorusSpreadUiChanged (float value);
    void fxChorusStaggerUiChanged (float value);
    void fxChorusTapsUiChanged (int value);
    void fxChorusTypeUiChanged (int value);
    void fxChorusLfoBUiChanged (float value);
    void fxChorusLfoTUiChanged (float value);
    void fxReverbLpfUiChanged (int value);
    void fxReverbHpfUiChanged (int value);
    void fxReverbTypeUiChanged (int value);
    void fxReverbSizeMinUiChanged (float value);
    void fxReverbSizeMaxUiChanged (float value);
    void fxReverbPredelayUiChanged (int value);
    void fxReverbModDepthUiChanged (float value);
    void fxReverbModRateUiChanged (float value);
    void fxReverbDiffusionUiChanged (float value);
    void fxReverbMixUiChanged (float value);
    void fxGlitchProbabilityMinUiChanged (float value);
    void fxGlitchProbabilityMaxUiChanged (float value);
    void fxGlitchWeightHoldLowUiChanged (float value);
    void fxGlitchWeightStutterLowUiChanged (float value);
    void fxGlitchWeightCrushLowUiChanged (float value);
    void fxGlitchWeightDropLowUiChanged (float value);
    void fxGlitchWeightHoldHighUiChanged (float value);
    void fxGlitchWeightStutterHighUiChanged (float value);
    void fxGlitchWeightCrushHighUiChanged (float value);
    void fxGlitchWeightDropHighUiChanged (float value);
    void fxGlitchDropKeepLevelMinUiChanged (float value);
    void fxGlitchDropKeepLevelMaxUiChanged (float value);
    void fxGlitchDropKeepTimeMinUiChanged (float value);
    void fxGlitchDropKeepTimeMaxUiChanged (float value);
    void fxGlitchCrushTimeMinUiChanged (float value);
    void fxGlitchCrushTimeMaxUiChanged (float value);
    void fxGlitchMicroloopSmplTMinUiChanged (float value);
    void fxGlitchMicroloopSmplTMaxUiChanged (float value);
    void fxGlitchMicroloopPlayTMinUiChanged (float value);
    void fxGlitchMicroloopPlayTMaxUiChanged (float value);
    void fxGlitchStutterSmplTMinUiChanged (float value);
    void fxGlitchStutterSmplTMaxUiChanged (float value);
    void fxGlitchStutterNumMinUiChanged (int value);
    void fxGlitchStutterNumMaxUiChanged (int value);
    void fxGlitchStutterWindowUiChanged (int value);

    void paint (juce::Graphics& g) override;
    void resized () override;
};